In [24]:
#mixed
#More with the numpy

In [25]:
import numpy as np


In [26]:
a = np.array([1, 2, 3, 4])

In [6]:
print(type(a), a.shape, a.dtype, a.ndim, a[0], a[1], a[2], a[3])

<class 'numpy.ndarray'> (4,) int32 1 1 2 3 4


In [7]:
#2d Array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
b

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
print(b.shape)

(2, 3)


In [11]:
#Create a 2 X 2 with all elements as Zeros
a = np.zeros([2, 2])
a

array([[0., 0.],
       [0., 0.]])

In [12]:
print(a)

[[0. 0.]
 [0. 0.]]


In [13]:
#With ones
 = np.ones([2, 2])
a

array([[1., 1.],
       [1., 1.]])

In [19]:
b = np.ones([2, 3])
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#Constant Array
c = np.full((2, 2), 7)
print(a)

[[7 7]
 [7 7]]


In [20]:
#Identity Matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
e = np.random.random((2, 2))
e

array([[0.32818994, 0.33346012],
       [0.25323737, 0.58326863]])

In [24]:
#Array Slicing

In [25]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
#Slicing it upto first 2 rows and 1 and 2 colums(we are counting from zero)
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [28]:
#We know that b[0][0] = a[0][1]
print(a[0][1])
b[0][0] = 77
print(a[0][1])

2
77


In [1]:
#Kyo ki wo isi ka part h same address h dono ki karlo change wo bi badal jayega


In [4]:
#View of a Rank





a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
#One Dimensional Vies of Second row of a 
row_r1 = a[1,:]
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [13]:
#Two Dimensional view of Second Row of a
row_r2 = a[1:2, : ]
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [14]:
#Upar wale instruction ko aise b hasil kara ja sakta h
row_r3 = a[[1],:]
print(row_r3, row_r3.shape)

[[5 6 7 8]] (1, 4)


In [15]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
#We can make same distinction in Column of Array

In [20]:
col_c1 = a[:, 1]
col_c2 = a[:,1:2]
col_c3 = a[:,[1]]
print(col_c1, col_c1.shape)
print(col_c2, col_c2.shape)
print(col_c3, col_c3.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [22]:
print(a)

#Slicing Using Integer Array Indexing

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [33]:
#We can also make subarrays following the same procedure
print([a[0, 0], a[1, 1], a[2, 0]])

1 4 5


In [36]:
#we need indices
#00 
#11 
#20 
b = a[[0, 1, 2], [0, 1, 0]]
print(b,b.shape)

[1 4 5] (3,)


In [38]:
#Using Integer Array Indexing we can reuse the same Array Elements
print(a[[0,0], [1, 1]])

[2 2]


In [41]:
print(np.array([a[0, 1], a[0, 1]]))

[2 2]


In [21]:
#Let's do something Boombastic


In [27]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
select = np.array([0, 1, 2])

In [29]:
print(a[np.arange(3),select])

[1 5 9]


In [30]:
a[np.arange(3), select] += 4
print(a[np.arange(3), select])

[ 5  9 13]


In [31]:
print(a)

[[ 5  2  3]
 [ 4  9  6]
 [ 7  8 13]
 [10 11 12]]


In [32]:
#Boolean Array Indexing
#Boolean Array Indexing let's you find the elements where condition is true

In [33]:
bool_indx = a > 8

In [34]:
print(bool_indx)

[[False False False]
 [False  True False]
 [False False  True]
 [ True  True  True]]


In [37]:
a = a[bool_indx]
a

array([ 9, 13, 10, 11, 12])

In [38]:
a

array([ 9, 13, 10, 11, 12])

In [40]:
b = np.array([[1, 2], [3, 4], [5, 6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
print(b[b > 2])

[3 4 5 6]


In [ ]:
#