In [3]:
#Do things with Datatypes
import numpy as np

In [4]:
x = np.array([1, 2, 3, 4])
x.dtype

dtype('int32')

In [5]:
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
x.dtype

dtype('float64')

In [11]:
x = np.array([1, 2, 3, 4, 5], dtype = np.float64)

In [12]:
x.dtype

dtype('float64')

In [13]:
#Array Maths
x = np.array([1, 2, 3, 4], dtype = np.float64)
print(x)
y = np.array([4, 3, 2, 1], dtype = np.float64)
print(y)

[1. 2. 3. 4.]
[4. 3. 2. 1.]


In [14]:
print(x + y)
print(np.add(x, y))

[5. 5. 5. 5.]
[5. 5. 5. 5.]


In [16]:
print(x - y)
print(np.subtract(x, y))


[-3. -1.  1.  3.]
[-3. -1.  1.  3.]


In [17]:
print(x * y)
print(np.multiply(x, y))

[4. 6. 6. 4.]
[4. 6. 6. 4.]


In [18]:
print(x / y)
print(np.divide(x, y))

[0.25       0.66666667 1.5        4.        ]
[0.25       0.66666667 1.5        4.        ]


In [19]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [20]:
print(np.sqrt(y))

[2.         1.73205081 1.41421356 1.        ]


In [21]:
#Dot product matrix Multiplication

In [22]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [23]:
v = np.array([9, 10])
w = np.array([11, 12])


In [25]:
print(v.dot(w))
print(np.dot(v, w))

219
219


In [26]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [27]:
#Vector and Matrix Multiplication
print(x.dot(v))

[29 67]


In [28]:
print(np.dot(x, v))

[29 67]


In [29]:
#Row wise and Column wise sum of Elements of 2D array
x

array([[1, 2],
       [3, 4]])

In [30]:
#All
print(np.sum(x))

10


In [31]:
#axis = 0 hoti h Columnwise sum k liye
#axis = 1 hoti h Row wise sum k liye
print(np.sum(x, axis = 0))

[4 6]


In [34]:
print(np.sum(x, axis = 1))

[3 7]


In [37]:
#transpose of a Matrix
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [38]:
print(x.T)

[[1 3]
 [2 4]]


In [39]:
#Broadcasting bahut powerful h
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
v = np.array([1, 0, 1])

In [41]:
v

array([1, 0, 1])

In [42]:
y = np.empty_like(x)
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
for i in range(4):
    y[i, :] = x[i, :] + v
print(v)    

[1 0 1]


In [44]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [45]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [46]:
#However when Matrix size is large running the loops might be costly so

In [48]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
v

array([1, 0, 1])

In [55]:
vv = np.tile(v, (4,1))
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [56]:
y = x + vv
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [57]:
#Now let's see the magic of Broadcasting
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [58]:
v

array([1, 0, 1])

In [59]:
y = x + v

In [60]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [61]:
v = [1,0]
y = x + v

ValueError: operands could not be broadcast together with shapes (4,3) (2,) 

In [62]:
#Applications of Broadcasting


In [64]:
v = np.array([1, 2, 3])
w = np.array([4, 5])
print(v*w)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [65]:
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [66]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
print(x+v)

[[2 4 6]
 [5 7 9]]


In [68]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
w

array([4, 5])

In [70]:
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [71]:
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [72]:
print(2*x)

[[ 2  4  6]
 [ 8 10 12]]
